### ISSUE TITLE
Cookie import fails with "validated: undefined"

### ISSUE THREAD

**Issue by EpicLPer** [tubearchivist/browser-extension#22]
Heya,

I just tried importing my cookies and I'm getting the following error inside the browser extension:
![image](https://github.com/tubearchivist/browser-extension/assets/8442196/511f7f72-13db-4345-babd-a6b98ddc38b8)

In the Inspect tab I get the message `{"message":{"cookie_import":"fail","cookie_validated":false}}`, the network tab tells me a `400 Bad Request` occured.

Not sure if I'm doing something wrong (again) tho :)

Thanks already!

**Comment by bbilly1** [comment]
Impossible to say without logs what's happening. Probably means invalid cookie? Sometimes doing this from a blank browser can help, where there has always only been one google account used. Or you can also use the manual import.

**Comment by DutchEllie** [comment]
I have the same issue, have been having it since forever and always just manually added the cookie, very annoying.
This is the log from when I tried to add the cookie using the extension:

```
cookie preview:

# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file! Do not edit.

.youtube.com    TRUE    /       FALSE   1719579328      SOCS    [REDACTED]
.youtube.com    TRUE    /       TRUE    0       YSC     [REDACTED]
.youtube.com    TRUE    /       FALSE   1720011328      CONSENT [REDACTED]
.youtube.com    TRUE    /       TRUE    1725
cookie: activated and stored in Redis
validating cookie
cookie file is invalid
cookie validation failed, exiting...
cookie: revoked
cookie: {'cookie_import': 'fail', 'cookie_validated': False}
[pid: 44|app: 0|req: 1359/1359] 10.0.0.38 () {64 vars in 1070 bytes} [Thu Aug 17 14:16:03 2023] PUT /api/cookie/ => generated 61 bytes in 101 msecs (HTTP/1.1 400) 9 headers in 357 bytes (1 switches on core 0)
```

It seems to just send bad data, not actually the full cookies file like it needs.

**Comment by grantterra** [comment]
I had the same issue.

<img width="1327" alt="Snipaste_2023-09-03_19-40-46" src="https://github.com/tubearchivist/browser-extension/assets/4091143/dac46c5a-370b-468e-b394-d68421492a75">

**Comment by 3urobeat** [comment]
I'm also experiencing this issue for months now.  
It did work as expected back in June and then suddenly failed.  
Tubearchivist on my server, as well as the browser extension, are on the newest versions.  
I have deleted all my YouTube cookies, did a fresh login - also no success.  

I'm using `LibreWolf Firefox 118.0.1-1` on `Linux 6.5.5-arch1-1`

**Comment by clb92** [comment]
I'm experiencing this in Chrome, but not in Firefox.

**Comment by bbilly1** [comment]
> It seems to just send bad data, not actually the full cookies file like it needs.

and

> I compared the original cookies stored in the browser, and it seems that TubeArchivist did not receive the last 54 characters in the cookie value.

as well as

> I can confirm the observation by grantterra, the cookie extracted by the extension is too short. 

you'll see in your log output `cookie preview`. so what is logged is only the first 200 characters (I think) from the complete cookie. as that is sensitive data, so this shouldn't be logged completely somewhere...

cookie building happens in background.js here: https://github.com/tubearchivist/browser-extension/blob/master/extension/background.js#L209

if anybody wants to investigate further.

**Comment by bbilly1** [comment]
Some investigation on the live stream could point towards that we limit our domain selection too much, and that www.youtube.com will get excluded. 

notes: https://github.com/Rob--W/cookie-manager/issues/26

some traceback:
```
/usr/local/lib/python3.11/http/cookiejar.py:2083: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/http/cookiejar.py", line 2056, in _really_load
    assert domain_specified == initial_dot
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

  _warn_unhandled_exception()
```

**Comment by Gentoli** [comment]
For me, looks like the extension included a cookie from the subdomain `payments.youtube.com` and yt-dlp is not happy with that. Removing it from the `POST /api/cookie/` works.

Because the validation is done by yt-dlp, before https://github.com/tubearchivist/tubearchivist/pull/669 which would log the error in the console, you could try capturing the cookie file sent by the extension from the extension developer console, then testing it with downloading any youtube video with a noop arg like `-F`, then it would give error like:
```
http.cookiejar.LoadError: invalid Netscape format cookies file 'C:\\Users\\<user>\\Desktop\\cookies.txt': 'payments.youtube.com\tTRUE\t/\tFALSE\t1711779732\tOTZ\t<some-value>'
```

**Comment by bbilly1** [comment]
Interesting, would make sense that I can't reproduce this, I probably won't have any payment subdomain cookies if I didn't make any payments on YT. Will ignoring all subdomains work? Or does this need some other processing?

**Comment by Gentoli** [comment]
Given yt-dlp is rejecting cookies from the subdomains, I think it's safe to remove all subdomains.

**Comment by CommanderRedYT** [comment]
I do not have any cookies on subdomains but it still fails. Both on firefox and chrome and with different accounts

**Comment by wolrah** [comment]
I can confirm that removing the payments.youtube.com cookie solved the problem for me.

**Comment by bbilly1** [comment]
Can somebody who can reproduce this check if the linked commit on the https://github.com/tubearchivist/browser-extension/tree/fix-cookie-domain branch fixes that?

This still syncs the cookie correctly for me.

**Comment by bbilly1** [comment]
assuming this has been fixed, update to v0.3.0

**Comment by ccfman2004** [comment]
Seems this issue is back on both Firefox and Chrome.  It stopped working on Firefox a few weeks ago but Chrome was working. Now neither are working.

`# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file! Do not edit.

.youtube.com    TRUE    /       TRUE    1753296799      VISITOR_INFO1_LIVE      aUp6m8dZzPQ
.youtube.com    TRUE    /       TRUE    1753296799      VISITOR_PRIVACY_METADATA        CgJVUxIEGgAgVw%3D%3D
.youtube.com    TRUE    /       TRUE    1753241785      _
cookie: activated and stored in Redis
validating cookie
/usr/local/lib/python3.11/http/cookiejar.py:2083: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/http/cookiejar.py", line 2056, in _really_load
    assert domain_specified == initial_dot
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

  _warn_unhandled_exception()
ERROR: invalid Netscape format cookies file <_io.StringIO object at 0x14f5d0a12f80>: 'www.youtube.com\tTRUE\t/\tFALSE\t1738584490\tOTZ\t7894808_76_76_104100_72_446760'
LL: failed to get info from youtube with message ERROR: invalid Netscape format cookies file <_io.StringIO object at 0x14f5d0a12f80>: 'www.youtube.com\tTRUE\t/\tFALSE\t1738584490\tOTZ\t7894808_76_76_104100_72_446760'
cookie validation failed, exiting...
cookie: revoked
cookie: {'cookie_import': 'fail', 'cookie_validated': False}
[pid: 4290|app: 0|req: 115344/115344] 10.0.0.135 () {50 vars in 818 bytes} [Fri Jan 24 13:57:49 2025] PUT /api/cookie/ => generated 61 bytes in 250 msecs (HTTP/1.1 400) 9 headers in 358 bytes (1 switches on core 0)`
